container: 'mcr.microsoft.com/dotnet/sdk:6.0'

stages:
- stage: continuous_integration
  displayName: 'Continuous Integration'
  jobs:
  - job: build
    displayName: Build
    pool: 
      vmImage: 'windows-latest'
    steps:
    - script: dotnet --version
      displayName: 'Check .Net version'
    - script: dotnet restore
      displayName: 'Restore Nuget packages'
    - script: dotnet build
      displayName: 'Build .Net Project'
    - script: dotnet run
      displayName: 'Run .NET Project'
